# language: node_js
# node_js:
#   - "stable"
# cache:
#   directories:
#   - node_modules
# script:
#   - npm run build-storybook
# deploy:
#   provider: pages
#   skip_cleanup: true
#   token: $github_token
#   local_dir: storybook-static
#   target_branch: gh-pages
#   on:
#     branch: test1
    
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI=true
script:
  - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: test1
  
  